

GRID_SIZE = 100
N = M = GRID_SIZE

INITIAL_BOB_COUNT = 100
P = INITIAL_BOB_COUNT

TICKS_PER_DAY = 100
D = TICKS_PER_DAY

FOOD_SPAWN_PER_DAY = 200
F = FOOD_SPAWN_PER_DAY

ENERGY_PER_FOOD = 100
Ef = ENERGY_PER_FOOD

BASE_BOB_ENERGY = 100
Espawn = BASE_BOB_ENERGY

MAX_BOB_ENERGY = 200
Emax = MAX_BOB_ENERGY

BIRTH_ENERGY_BOB = 50
Ebirth = BIRTH_ENERGY_BOB

REPRODUCTION_ENERGY = 150
Emother = REPRODUCTION_ENERGY

INITIAL_BOB_SPEED = 1
V = INITIAL_BOB_SPEED

SPEED_MUTATION_RATE = 0.1
MutV = SPEED_MUTATION_RATE

ENERGY_SPENT_IDLE = 1/2
Etmin = ENERGY_SPENT_IDLE

VISION_RANGE = 0
VISION_PENALTY = 1/5

Pv = VISION_PENALTY
REPRODUCTION_ENERGY_TWO = 100

Emother2 = REPRODUCTION_ENERGY_TWO
SEXUAL_BIRTH_ENERGY = 100

Ebirth2 = SEXUAL_BIRTH_ENERGY
